DROP DATABASE IF EXISTS shopping_cart;
DROP USER IF EXISTS `dbGOD`@`%`;
DROP USER IF EXISTS `dbUser`@`%`;

CREATE DATABASE IF NOT EXISTS shopping_cart CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `dbGOD`@`%` IDENTIFIED WITH mysql_native_password BY 'GODpassword';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `shopping_cart`.* TO `dbGOD`@`%`;

CREATE USER IF NOT EXISTS `dbUser`@`%` IDENTIFIED WITH mysql_native_password BY 'userpassword';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `shopping_cart`.* TO `dbUser`@`%`;

FLUSH PRIVILEGES;